// Rangos: letras, umbrales, colores y nombres por modalidad.

var rangos = ["E", "D", "C", "B", "A", "S", "Z"],
  nivelUmbral = { E: 50, D: 100, C: 140, B: 180, A: 220, S: 260 },
  colorRango = {
    E: "#7b8290",
    D: "#8b93a8",
    C: "#3ecf8e",
    B: "#4f9dff",
    A: "#b084f5",
    S: "#ffb84f",
    Z: "#ff5c7a",
  },
  sdcTitulos = {
    bodyweight: {
      E: "Suelo",
      D: "Eje",
      C: "Recorrido",
      B: "Palanca",
      A: "Lado",
      S: "Sostén",
      Z: "Oficio",
    },
    gym: { E: "Barra", D: "Disco", C: "Forma", B: "Carga", A: "Tope", S: "Máxima", Z: "Hierro" },
    flow: {
      E: "Gateo",
      D: "Apoyo",
      C: "Giro",
      B: "Enlace",
      A: "Inversión",
      S: "Quietud",
      Z: "Vuelo",
    },
  },
  sdcDescs = {
    bodyweight: {
      E: "Regresión base — el suelo te ayuda",
      D: "Control motor inicial — rango parcial asistido",
      C: "Patrón estándar — rango completo de movimiento",
      B: "Intensificación — declinado, desequilibrio y pausas",
      A: "Alta fuerza relativa — unilateral progresivo",
      S: "Dominio motriz — unilateral estricto e isometría",
      Z: "Variantes compuestas — las metas salen de tus récords",
    },
    gym: {
      E: "Aprendes el gesto — la barra sola, sin carga",
      D: "Primera carga real — técnica antes que peso",
      C: "Rango completo bajo carga — sin acortar el recorrido",
      B: "Progresión de peso — el mismo gesto, más caro",
      A: "Cerca del máximo — series cortas y pesadas",
      S: "Trabajo máximo — control absoluto de la carga",
      Z: "Tus propias variantes — las metas salen de tus récords",
    },
    flow: {
      E: "Contacto con el suelo — gateo y apoyos básicos",
      D: "Dónde va el peso — apoyos firmes y conscientes",
      C: "Rotación completa — el rango entero de la articulación",
      B: "Encadenar sin apoyar — el movimiento no se corta",
      A: "Inversión — el peso pasa a las manos",
      S: "Sostenes largos — quedarte quieto es lo difícil",
      Z: "Secuencias propias — las metas salen de tus récords",
    },
  },
  metrosPorPaso = 0.75,
  escalaCaminante = [
    { name: "Primeros Pasos", minKm: 0 },
    { name: "Caminante", minKm: 5 },
    { name: "Piernas Hechas", minKm: 20 },
    { name: "Kilometrero", minKm: 50 },
    { name: "Fondista", minKm: 100 },
    { name: "Paso Largo", minKm: 200 },
    { name: "Sin Distancia", minKm: 350 },
  ];

export { rangos, nivelUmbral, colorRango, sdcTitulos, sdcDescs, metrosPorPaso, escalaCaminante };
